version: "3.8"

services:
  chatbot:
    build:
      context: ./ChatbotTest
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - chatbotnet

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434" # Ollama default API port
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - chatbotnet

  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678" # n8n web UI
    environment:
      - GENERIC_TIMEZONE=Europe/London
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=your_password
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - chatbotnet

networks:
  chatbotnet:
    driver: bridge

volumes:
  ollama_data:
  n8n_data:
