version: "3.8"

services:
  backend:
    build:
      context: ./ChatbotTest
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - chatbotnet


networks:
  chatbotnet:
    driver: bridge
